os: linux
dist: jammy
language: php
php:
  - 8.2

cache:
  npm: true
  yarn: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.yarn"
  - "./private/node_modules"
  - "./vendor"

before_install:
- phpenv config-rm xdebug.ini

install:
- composer install

stages:
  - name: Lint
    if: branch IS present
  - name: Update Draft Release [DEV]
    if: branch = develop AND type != pull_request
  - name: Update Draft Release [STG]
    if: branch = staging AND type != pull_request
  - name: Update Draft Release [PRD]
    if: branch = main AND type != pull_request

jobs:
  include:
  - stage: Lint
    script:
    - composer lint

  - stage: Update Draft Release [DEV]
    script:
    - zip -r ../humanity-petitions-salesforce-adapter-develop.zip ./ -x .\* -x CHANGELOG.md -x CODE_OF_CONDUCT.md -x composer.json -x composer.lock -x CONTRIBUTING.md -x LICENSE.md -x phpcs.xml -x SECURITY.md -x docs\* -x vendor\*
    deploy:
      provider: releases
      token:
        secure: "rmlS53Wbmgx0YyE7TB2FA/8hmuLV5APLJ2x8PC8GltoppLIvwoZPvWV06vT6Fz5UTdETDbri6Nrbh/OBprbJPhrzpxTAQz8eD9UyRhhpHLqav6c/v5ZgOHG0rS0eg/vHtcFuQqcf5iQc7GW9wsDKanhSTOeIhqNx4g/lXJgH+oNsmGJH69MdU76dqnngdlgQ8G5ntb7j5hYKSHMwfJRAo3KGUjUhGbr55w8tMM7lK7L58VZbpfQvtgBnCD64WLhPOoEyq25CmD4w5O4T9ApTG5ddZP/t8we6DSvafKAk9Bi0EIJdmEZojk1vUkD6pYRbUGRFZAO6Ilcfk20SP/UzSKZZ0Cu9ikRU5KfV/LSvRc5L8IYuhC4UXYL1ZVKxtV7P4RxShb+VzF4ffFPFiataf+BfBSvSlk1qyr3pr1+8ZETMN9LRqrlxdpxVlmC/kjsanwlkK16nIQ1FE5B24jTgn3Eri9G9kTaB4rBHG85+kPxk7OqjHNAebVfEpTDX937hyvbsc7jc/BIy+HOlx+nK9RLTS2jmmZjhdgVfLy0LtXdGpwztBPXgtsmt+4JDUVL1Nro5p1AFWy/5b6yxiW79cvmv+8d02/lDNsQz8G2eb5/QGp7JxpdX52aCFxoz4kaD9SPQ6UGQPoNj4XpXeglSnuy3+ZoWDFX8Pbqs16gLUeY="
      file: "../humanity-petitions-salesforce-adapter-develop.zip"
      skip_cleanup: true
      draft: true
      overwrite: true
      on:
        repo: amnestywebsite/humanity-petitions-salesforce-adapter
        branch: develop

  - stage: Update Draft Release [STG]
    script:
    - zip -r ../humanity-petitions-salesforce-adapter-staging.zip ./ -x .\* -x CHANGELOG.md -x CODE_OF_CONDUCT.md -x composer.json -x composer.lock -x CONTRIBUTING.md -x LICENSE.md -x phpcs.xml -x SECURITY.md -x docs\* -x vendor\*
    deploy:
      provider: releases
      token:
        secure: "rmlS53Wbmgx0YyE7TB2FA/8hmuLV5APLJ2x8PC8GltoppLIvwoZPvWV06vT6Fz5UTdETDbri6Nrbh/OBprbJPhrzpxTAQz8eD9UyRhhpHLqav6c/v5ZgOHG0rS0eg/vHtcFuQqcf5iQc7GW9wsDKanhSTOeIhqNx4g/lXJgH+oNsmGJH69MdU76dqnngdlgQ8G5ntb7j5hYKSHMwfJRAo3KGUjUhGbr55w8tMM7lK7L58VZbpfQvtgBnCD64WLhPOoEyq25CmD4w5O4T9ApTG5ddZP/t8we6DSvafKAk9Bi0EIJdmEZojk1vUkD6pYRbUGRFZAO6Ilcfk20SP/UzSKZZ0Cu9ikRU5KfV/LSvRc5L8IYuhC4UXYL1ZVKxtV7P4RxShb+VzF4ffFPFiataf+BfBSvSlk1qyr3pr1+8ZETMN9LRqrlxdpxVlmC/kjsanwlkK16nIQ1FE5B24jTgn3Eri9G9kTaB4rBHG85+kPxk7OqjHNAebVfEpTDX937hyvbsc7jc/BIy+HOlx+nK9RLTS2jmmZjhdgVfLy0LtXdGpwztBPXgtsmt+4JDUVL1Nro5p1AFWy/5b6yxiW79cvmv+8d02/lDNsQz8G2eb5/QGp7JxpdX52aCFxoz4kaD9SPQ6UGQPoNj4XpXeglSnuy3+ZoWDFX8Pbqs16gLUeY="
      file: "../humanity-petitions-salesforce-adapter-staging.zip"
      skip_cleanup: true
      draft: true
      overwrite: true
      on:
        repo: amnestywebsite/humanity-petitions-salesforce-adapter
        branch: staging

  - stage: Update Draft Release [PRD]
    script:
    - zip -r ../humanity-petitions-salesforce-adapter.zip ./ -x .\* -x CHANGELOG.md -x CODE_OF_CONDUCT.md -x composer.json -x composer.lock -x CONTRIBUTING.md -x LICENSE.md -x phpcs.xml -x SECURITY.md -x docs\* -x vendor\*
    deploy:
      provider: releases
      token:
        secure: "rmlS53Wbmgx0YyE7TB2FA/8hmuLV5APLJ2x8PC8GltoppLIvwoZPvWV06vT6Fz5UTdETDbri6Nrbh/OBprbJPhrzpxTAQz8eD9UyRhhpHLqav6c/v5ZgOHG0rS0eg/vHtcFuQqcf5iQc7GW9wsDKanhSTOeIhqNx4g/lXJgH+oNsmGJH69MdU76dqnngdlgQ8G5ntb7j5hYKSHMwfJRAo3KGUjUhGbr55w8tMM7lK7L58VZbpfQvtgBnCD64WLhPOoEyq25CmD4w5O4T9ApTG5ddZP/t8we6DSvafKAk9Bi0EIJdmEZojk1vUkD6pYRbUGRFZAO6Ilcfk20SP/UzSKZZ0Cu9ikRU5KfV/LSvRc5L8IYuhC4UXYL1ZVKxtV7P4RxShb+VzF4ffFPFiataf+BfBSvSlk1qyr3pr1+8ZETMN9LRqrlxdpxVlmC/kjsanwlkK16nIQ1FE5B24jTgn3Eri9G9kTaB4rBHG85+kPxk7OqjHNAebVfEpTDX937hyvbsc7jc/BIy+HOlx+nK9RLTS2jmmZjhdgVfLy0LtXdGpwztBPXgtsmt+4JDUVL1Nro5p1AFWy/5b6yxiW79cvmv+8d02/lDNsQz8G2eb5/QGp7JxpdX52aCFxoz4kaD9SPQ6UGQPoNj4XpXeglSnuy3+ZoWDFX8Pbqs16gLUeY="
      file: "../humanity-petitions-salesforce-adapter.zip"
      skip_cleanup: true
      draft: true
      overwrite: true
      on:
        repo: amnestywebsite/humanity-petitions-salesforce-adapter
        branch: main
